[package]
name = "louvain-application"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# Workspace dependencies
louvain-domain = { path = "../domain" }

# External dependencies
rand = "0.8.5"

